### ISSUE TITLE
Methods with default values are documented multiple times

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/scala3doc#109]
![image](https://user-images.githubusercontent.com/48246851/90108831-2d44f100-dd4b-11ea-9c8f-897480efa925.png)

**Comment by abgruszecki** [comment]
The latter symbols are actually the default values of n-th argument *. We definitely don't want to display them (I'm kind of surprised they aren't `Synthetic`) and we should think about whether we want to explicitly mark appropriate parameters as optional.

* i.e. on the JVM we actually compile each default value to a method and manually insert a call to this method wherever the "parent" method is called.

**Comment by pikinier20** [comment]
These symbols don't have any flag that would help us in filtering them. The only flag set is `<method>`

**Comment by abgruszecki** [comment]
I checked Dotty source (comments specifically) and it looks like the _parameters_ of a method should have a special flag (`HasDefault`), but not the methods that implement the default values for each parameter. In that case, I think we need to filter them out based on their names ending in `$default$N`.
