### ISSUE TITLE
Type signature is missing information

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/scala3doc#112]
```Scala
opaque type Permissions = Int
opaque type PermissionChoice = Int
opaque type Permission <: Permissions & PermissionChoice = Int
```

renders as:
```Scala
...
opaque type Permission <: Permissions & PermissionChoice
```

**Comment by abgruszecki** [comment]
Is this still up to date? This is how I'd expect `Permission` to render. The intention behind opaque types is that their implementation is hidden, so we shouldn't show it in the documentation, even if it can be seen in the source.

**Comment by pikinier20** [comment]
> Is this still up to date? This is how I'd expect `Permission` to render. The intention behind opaque types is that their implementation is hidden, so we shouldn't show it in the documentation, even if it can be seen in the source.

You're right, we can close that.
