### ISSUE TITLE
Reuse Markdown reference-style links for definition linking

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#120]
Markdown supports links with the following syntax: `[link]` See [reference](https://spec.commonmark.org/0.29/#shortcut-reference-link). Those aren't normal links - they are _reference_ links instead.

On one hand, the syntax for them is similar enough to how links looked in Wiki syntax (`[[List]]`) that it'd be nice to reuse them. Right now we need to write `()[List]`, which is just kind of ugly.

On the other hand, we shouldn't interfere too much with Markdown features such as reference-based links.

I think what we can do is we can support links of the form `[@List]`, which will be equivalent to old `[[List]]` Wiki-syntax links while also not interfering too much with Markdown references (since I'd expect it should be easy to avoid naming references with a name starting with a `@`).

**Comment by TheElectronWill** [comment]
Yes please! I like that proposal :)
