### ISSUE TITLE
Figure out how to initially release Scala3doc

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#124]
Both the SBT plugin, as well as Scala3doc itself.

**Comment by julienrf** [comment]
I find it a bit less practical if we have to rely on an additional plugin. Currently, it is extremely convenient to be able to just run `doc` from within sbt on any Scala project and get the API documentation. Could Scala3doc be bundled within scala-compiler.jar?

**Comment by abgruszecki** [comment]
I didn't know that was possible. Do you know where this `doc` task is defined?

**Comment by abgruszecki** [comment]
And yes, the plan is eventually to distribute scala3doc together with the compiler, like dottydoc is distributed right now - this is only the task for the first milestone, to enable people to try out the new tool

**Comment by julienrf** [comment]
It’s defined here: https://github.com/sbt/sbt/blob/7f0d97acdf2faa19507ba33a76886a852e53c8a3/main/src/main/scala/sbt/Defaults.scala#L1833-L1874

**Comment by romanowski** [comment]
We are released alongside compiler now.
