### ISSUE TITLE
Write "how to get started" documentation

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#137]
How to generate documentation for your project.

How to view the documentation.

How to add project documentation (Markdown files).

**Comment by romanowski** [comment]
I think we should also include samples how to deploy the docs to e.g. gh-pages using Guthub Actions or Travis

**Comment by abgruszecki** [comment]
That  sounds quite useful! It'd be an easy way for project maintainers to publicly share their documentation, which would help us discuss any issues that they see.
