### ISSUE TITLE
Show declaration before documentation

### ISSUE THREAD

**Issue by TheElectronWill** [lampepfl/scala3doc#139]
Dokka outputs things like:
```
This class does x y z.
Also, <insert long explanation>

class C extends D with E
```

In Scaladoc the documentation is shown under the declaration. I find that better (habit perhaps? I've noticed that Javadoc and Pydoc do that too).
```
class C extends D with E

This class does x y z.
Also, <insert long explanation>
```

Doing it that way would also put the full declaration of a top-level class/trait/etc.  just under the page's title, instead of after 40 lines of doc. I think that it would be a good thing.

**Comment by abgruszecki** [comment]
This might be a good idea.

Another argument is that overloaded methods show multiple signatures one-after-another. If we first display the signature and then the documentation, then the signature acts as a "header" for the doc.

**Comment by romanowski** [comment]
We are doing it for a while now :)
