### ISSUE TITLE
Links to external documentation won't work until Dokka release

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/scala3doc#141]
Linking to external documentation in Dokka should work automatically after providing proper links into configuration, but there's bug in our version of dokka that generates wrong links. However, this bug is already solved and after new release we can add some default links e.g. to std lib documentation. (it will work only for dokka-generated documentations for now)

**Comment by TheElectronWill** [comment]
Does it work now?

**Comment by romanowski** [comment]
Yes.
