### ISSUE TITLE
Synthetic "super" methods should not be displayed as inherited

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#145]
See: https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/self/scala3doc/example/level2/-documentation/index.html#scala.collection/SeqOps/scala$collection$SeqOps$$super$sizeCompare/#/PointingToDeclaration/scala.collection.SeqOps.super$scala$collection$SeqOps$$sizeCompare/scala.Int/[scala.collection.Iterable]

I think those may be filtered out by checking for the `Bridge` flag.

**Comment by pikinier20** [comment]
Unfortunately, flag Bridge is not set in theses cases. I've checked flags in internal API and the only flags that are set are:
`<method>, <touched>`
