### ISSUE TITLE
Some inherited methods don't display properly

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#174]
See    https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/self/scala3doc/example/-documentation-inheritance/index.html
  
Some names are larger and bold, while others aren't.
  
Seems to be releated to whether there is a page for the method in the class it was inherited from, or not.
  
Cmp:

* https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/self/scala3doc/example/-documentation-inheritance/index.html#example.level2/Documentation/methodsWithDefault/#/PointingToDeclaration/example.level2.Documentation.methodsWithDefault/scala.Nothing/[scala.Int]
* https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/self/scala3doc/example/-documentation-inheritance/index.html#scala.collection/Iterable/collectionClassName/#/PointingToDeclaration/scala.collection.Iterable.collectionClassName//[]

**Comment by pikinier20** [comment]
Yes, it's because we convert links to plain text if they couldn't be resolved  and some css style doesnt apply
