### ISSUE TITLE
Included documentation support

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/scala3doc#18]
We have to decide how to implement included documentation. There are at least two ways:

- we can do it as in scaladoc - user needs to define in config path to doc and place in code where to include it
- we can do it as in dokka - user only defines path to doc and information about destination, stays in file - this approach however changes format of included files

We can also invent something else

**Comment by romanowski** [comment]
@pikinier20 is there anything more needed after #45 is merged?

**Comment by pikinier20** [comment]
@romanowski I think that static sites can easily replace included documentation from scaladoc
