### ISSUE TITLE
Document our integration with dotty-stb

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#222]
E.g. why we need to add `--+DOC+` in our documentation

Probbaly we can rethink if we can do that integration better

**Comment by abgruszecki** [comment]
See comment https://github.com/lampepfl/dotty/pull/10092#discussion_r514389311 and issue https://github.com/lampepfl/dotty/issues/10119.

**Comment by abgruszecki** [comment]
No longer relevant.
