### ISSUE TITLE
Scala3doc is skipping backticks literal identifiers

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/scala3doc#235]
See [the failing test](https://github.com/lampepfl/dotty/blob/81e093876140faa7ddd6feb457fdc75e1110bff0/scala3doc-testcases/src/tests/complexNames.scala#L9-L11).
For identifiers that cannot be expressed without backticks scala3doc shouldn't skip them as it can lead to ambiguities and straight up incorrect signatures.

**Comment by Kordyjan** [comment]
I think the simplest solution for that would be to wrap all identifiers that desn't match some regex in backticks during generation of signatures.
This regex would probably look something like that: `(?:\w+)(?:_[^\[\(\s\w]+)|\w+|[^\[\(\s\w]+`.

**Comment by romanowski** [comment]
Moved to https://github.com/lampepfl/dotty/issues/11108
