### ISSUE TITLE
Proper raporting in scala3doc

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#238]
We should provide a way to properly raport errors and warnings similarly to `Reporter` in compiler.

We shoudl be able to report errors from .scala files as well as markdown and html files. 

There are various places where reporting needs to be rewritten within code (usually marked with this issue number)

**Comment by abgruszecki** [comment]
I've opened  #187 some time ago, where I suggested how to solve this. @romanowski: do you think it's feasible to do what I suggest there?

**Comment by abgruszecki** [comment]
I guess we can close this?
