### ISSUE TITLE
 we should include documentation from overriden member when new one is not provided

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#251]
In case like below in scaladoc:

```scala
trait A:
 /**
   * A doc for foo
   */
 def foo: Int

class B extends A:
 override def foo = 123
```
`B.foo` will have documentation (`A doc for foo`) from parent included. Shoudl scala3doc do the same?

**Comment by romanowski** [comment]
documentation should inherit both main text and each parameters if not defined.

**Comment by abgruszecki** [comment]
Are you certain that Scaladoc duplicates documentation like that? There's a special `@inheritdoc` "instruction" in Scaladoc that manually tells it to copy overriden definition's doc, and I've seen it applied by itself, which makes me think inheriting doc is not the default behaviour.
