### ISSUE TITLE
access denied when accessing scala3doc.s3.eu-central-1.amazonaws.com

### ISSUE THREAD

**Issue by robstoll** [lampepfl/scala3doc#253]
I wanted to take a look at https://scala3doc.s3.eu-central-1.amazonaws.com/pr-123/self/main/index.html 

but I get
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C9478774655DA939</RequestId><HostId>8+CM3TNz1CVGZiTQuZX9sItSCRFEnmCOpv7zjK0a98eBKV36nqrYFndLcG9ZchMd+1tzNjQfTVQ=</HostId></Error>
```

**Comment by romanowski** [comment]
After the migration to `dotty` repository we alsu nice a bit different address. You can see the documentation  at [https://scala3doc.virtuslab.com/pr-master/self/docs/index.html](https://scala3doc.virtuslab.com/pr-master/self/docs/index.html)

**Comment by romanowski** [comment]
I've also change a `readme.md` no to cause confusion.

**Comment by robstoll** [comment]
btw.I get ResourceNotFound for almost all url:
- https://scala3doc.virtuslab.com/master/scala3/main/index.html
- https://scala3doc.virtuslab.com/master/self/main/index.html 
- https://scala3doc.virtuslab.com/master/testcases/main/index.html

=> maybe because of bad luck and a deployment just happens but maybe also a general bug
