### ISSUE TITLE
Show annotations for class-likes and members

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#58]

**Comment by pikinier20** [comment]
https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/model/additionalExtras.kt
https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/signatures/JvmSignatureUtils.kt
https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/signatures/KotlinSignatureUtils.kt

https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt

There's extra property Annotations defined in additionalExtras.kt. To show annotation you need to parse it in TastyParser and add filled extra to documentable. Then you need to implement ScalaSignatureUtils extending JvmSignatureUtils (you can look how it's done in KotlinSignatureUtils). The last step is to use annotationBlock/annotationinline methods in ScalaSignatureProvider (again you can see usage in KotlinSignatureProvider). 

There might be problem with implementing extension methods defined in JvmSignatureUtils - if so, make some adapter in DokkaJavaApi.
