### ISSUE TITLE
Companion object should be first class members

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#60]
Goes for both class members and package members.

**Comment by romanowski** [comment]
Example of the problem:
`scala.Tuple`

**Comment by romanowski** [comment]
So we show them in e.g. package list
![Screenshot from 2020-08-07 10-30-31](https://user-images.githubusercontent.com/3967938/89626181-4821ec00-d899-11ea-9e90-13f99496b40e.png)
