### ISSUE TITLE
Document a CLI interface with examples, add usage to parameters and test if it works

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#69]

**Comment by romanowski** [comment]
My plan was to have only one entry point to application that is aligned with CLI interface. 

Do we need anything more sophisticated then [current code]( https://github.com/VirtusLab/dotty-dokka/blob/master/src/main/scala/dotty/dokka/Main.scala#L20-L51)?

If not, then probably we need to fix usage, documentation and test it.

From my side we should include some kind of packaging probably using `coursier.
