### ISSUE TITLE
Take imports into account when resolving links

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#80]

**Comment by romanowski** [comment]
@abgruszecki could you provide some example?

**Comment by abgruszecki** [comment]
This issue was about making the following work:

```scala
import scala.concurrent.Await

/** Uses [[Await]]. */
def foo() = ???
```

The imports aren't actually stored in Tasty though at the moment. I think we may close this issue, implementing it would be a significant amount of work and it's just a convenience feature.

**Comment by romanowski** [comment]
In such case I am removing it from current milestone.
