### ISSUE TITLE
Complete support for types

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#84]
Currently we do not support all types (see usage of [this method](https://github.com/VirtusLab/dotty-dokka/blob/master/src/main/scala/dotty/dokka/tasty/TypesSupport.scala#L38-L40)).

We should add types for

- [x] `TypeLambda`
- [x] `Refinement`
- [x] Support for syntax for trains (`(Int, String)` instead of `Tuple2[Int, String]`)
- [x] `TypeRef` in cases non-trivial qualifier
- [x] `TermRef`
- [x] `TermRef`

Examples can be found by examining output of generating documentation of e.g. Standard Library. 

Logs will contain lines like:  `WARN: Unsupported type: TypeRef: x`.

**Comment by abgruszecki** [comment]
Sub-issues:
- [x] https://github.com/VirtusLab/dotty-dokka/issues/89
- [x] https://github.com/VirtusLab/dotty-dokka/issues/90
- [ ] https://github.com/VirtusLab/dotty-dokka/issues/91
- [x] https://github.com/VirtusLab/dotty-dokka/issues/92
- [x] https://github.com/VirtusLab/dotty-dokka/issues/93
