### ISSUE TITLE
Design search / grouping feature for members

### ISSUE THREAD

**Issue by romanowski** [lampepfl/scala3doc#85]

**Comment by romanowski** [comment]
Scaladoc has a feature to group / search group members.
![Screenshot from 2020-08-07 11-39-57](https://user-images.githubusercontent.com/3967938/89632821-2463a380-d8a3-11ea-8cf0-3ed86cba242b.png)

**Comment by BarkingBad** [comment]
Isn't it resolved completely or at least there is progress on that task? We have this search:
![obraz](https://user-images.githubusercontent.com/32793002/99390332-bf274180-28d8-11eb-84c6-bface7e01650.png)
