### ISSUE TITLE
Consider how to link companions

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#86]
With Dokka, we can consider new ways to display companion objects/classes.

In Scala, it's quite often the case that only one of the above is important - i.e., the class is a trivial case class and the companion has all the related functions.

Could such cases look better in documentation if we displayed members of companion objects as tabs on the companion class' page?

It'd be good to have real-world examples of the above before we change anything. Perhaps this is something we should ask on Scala Contributors about.

**Comment by romanowski** [comment]
If we just add Icons to exisiting docs would it be sufficient?

**Comment by abgruszecki** [comment]
Yeah, I don't think we want to do anything fancy about this issue at this point.

**Comment by romanowski** [comment]
Closing in favour of #119
