### ISSUE TITLE
Show polyfunction types in signatures

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/scala3doc#93]
Example:

```scala
type F = [X] => (x: X) => List[X]
```

Note that this isn't the same as a type lambda, and vice versa.

**Comment by pikinier20** [comment]
Currently these types are printed: 
```Scala
type F = PolyFunction { def apply[X](x: X): List[X] }
```
I think next step is to transform it into syntax sugar so it's part of #91

**Comment by abgruszecki** [comment]
Yes, I think it can be considered syntax sugar. One can write `type F = PolyFunction { def apply[X](x: X): List[X] }` in source and we should display it as `[X] => X => List[X]`.
